#!/bin/bash
declare -a messages=(
    "Rule 1: The Doctor lies. This test does not @channel"
    "I am and always will be the optimist. The hoper of far-flung hopes and the dreamer of improbable dreams. Currently I dream that this test will pass @channel"
    "@channel, there’s always something to look at if you open your eyes! For example, I opened mine and a test failed"
    "Yes, we're tired. Yes, there is no relief. Yes, the failed tests keep coming after us time after time after time. And yes, we are still expected to do our jobs @channel!"
    "The difference is, my flaws are personal, yours are professional @channel. Just have a look at the tests!"
    "@channel, you keep my tests passing. I need my tests to pass"
    "What we got here is failure to test @channel"
    "You can't handle the test! @channel"
    "Mama always said life was like a box of tests. You never know what you're gonna get. I got failed tests... @channel"
    "I see failed tests @channel"
    "@channel, we have a problem"
    "You've got to ask yourself one question: 'Do I feel that the tests passed?'. Well, do ya, punk?"
    "Say hello to my little test @channel!"
    "@channel listen to them. Failing tests of the night. What music they make"
    "A failed test. Shaken, not stirred @channel"
    "Well @channel, we may not have parted on the best of terms. I realize certain words were exchanged. Also, certain... tests"
    "I don't mean to alarm anybody @channel, but I think we have failed tests"
    "We have a reputation @channel! ACE gets it done, is the talk"
    "Time for some thrilling heroics @channel"
    "A test failed... have you tried to reverse the polarity of the neutron flow? @channel"
    "It's kind of exciting, isn't it @channel? Breaking the tests"
    "These failing tests are making me angry @channel. You won't like me when I'm angry"
    "A great man is always willing to fix a test @channel"
    "To pass, or not to pass, that is the question. @channel, I think we just got an answer..."
    "That's one small stumble for a man, one giant faceplant for a corporation @channel"
    "The only failure is not to fix @channel"
    "Salvador Dali once said 'Have no fear of perfection, you'll never reach it'. This is especially true for whoever broke my test @channel"
    "Everything negative – pressure, challenges, failed tests – is all an opportunity for you to rise @channel"
    "I like criticism. It makes you strong. So here is one: Fix that damn failed test @channel!"
    "Don’t testing ever have an end? I suppose not. Someone else always has to carry on the testing @channel"
    "Doublethink means the power of holding two contradictory beliefs in one's mind simultaneously, and accepting both of them. Like not fixing this failed test and justifying doing something else @channel"
    "It's a beautiful thing, the destruction of tests @channel"
    "We do not merely destroy our failed tests; we change them @channel"
    "Sanity is not statistical, but test pass rates are @channel"
)
echo ${messages[$RANDOM % ${#messages[@]}]}